# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

        # This restore everything in the solution file
      - name: Restore dependencies
        run: dotnet restore suppfly.slnx

        # This builds all projects in solution file
      - name: Build
        run: dotnet build suppfly.slnx --no-restore

        # Test files
      - name: Test
        run: dotnet test suppfly.slnx --no-build --verbosity normal
